          DSK TIMEIISETUP
          STR "OBJ/MAIN.L",00
          STR "OBJ/SETDATE.L",00
          STR "OBJ/DATETIME.L",00
          STR "OBJ/TIMEII.L",00
          STR "OBJ/INSTGUI.L",00
          STR "OBJ/INSTALL.L",00
          STR "OBJ/CNVANDCHCK.L",00
          STR "OBJ/INOUTDATA.L",00
          STR "OBJ/STR.L",00
          STR "OBJ/ASC.L",00
          STR "OBJ/MEM.L",00
          STR "OBJ/FORMS.L",00
          BRK
